doan_qlDuan_CNTT/doan_qlDuan_CNTT/doan_qlDuan_CNTT/Areas/Admin/Controllers/ChiTietDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using doan_qlDuan_CNTT.Areas.Admin.Models;
namespace doan_qlDuan_CNTT.Areas.Admin.Controllers
{
    public class ChiTietDonHangController : Controller
    {
        AdminDataContext db = new AdminDataContext();

        // GET: Admin/ChiTietDonHang
        public ActionResult Index(int mdh)
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                var ctdh = db.CTDONHANGs.Where(x => x.MaDH == mdh).ToList();
                return PartialView("Index", ctdh);
            }
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                return View();
            }
        }
        [HandleError]
        [HttpPost]
        public ActionResult Create(CTDONHANG createctdh)
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.CTDONHANGs.InsertOnSubmit(createctdh);
                    db.SubmitChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
    }
}

doan_qlDuan_CNTT/doan_qlDuan_CNTT/doan_qlDuan_CNTT/Areas/Admin/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using doan_qlDuan_CNTT.Areas.Admin.Models;


namespace doan_qlDuan_CNTT.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
        AdminDataContext db = new AdminDataContext();

        // GET: Admin/DonHang
        public ActionResult Index()
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                List<XemDonHangResult> model = db.XemDonHang().ToList();

                return View(model);
            }
        }
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                return View();
            }
        }
        [HandleError]
        [HttpPost]
        public ActionResult Create(DONHANG createdh)
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.DONHANGs.InsertOnSubmit(createdh);
                    db.SubmitChanges();
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
        [HandleError]
        public ActionResult Edit(int mdh)
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                DONHANG dh = db.DONHANGs.FirstOrDefault(p => p.MaDH == mdh);
                if (Request.Form.Count == 0)
                {
                    return View(dh);
                }

                string ngaymua = Request.Form["NgayMua"];
                string ngaydukiengiao = Request.Form["NgayDuKienGiao"];
                string tinhtrang = Request.Form["TinhTrang"];
                string makh = Request.Form["MaKH"];

                dh.NgayMua  = DateTime.Parse(ngaymua);
                dh.NgayDuKienGiao= DateTime.Parse(ngaydukiengiao);
                dh.TinhTrang =bool.Parse(tinhtrang);
                dh.MaKH = int.Parse(makh);

                db.SubmitChanges();
                return RedirectToAction("Index");
            }
        }
        [HandleError]
        public ActionResult Delete(int mdh)
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                var model = db.DONHANGs.SingleOrDefault(h => h.MaDH.Equals(mdh));
                try
                {
                    if (model != null)
                    {
                        db.DONHANGs.DeleteOnSubmit(model);
                        db.SubmitChanges();
                        return RedirectToAction("Index", "DonHang", new { error = "Xoá đơn hàng" });
                    }
                    else
                    {
                        return RedirectToAction("Index", "DonHang", new { error = "Đơn hàng không tồn tại." });
                    }
                }
                catch (Exception)
                {
                    return RedirectToAction("Index", "DonHang", new { error = "Không thể xoá đơn hàng." });
                }
            }
        }
        public ActionResult Details (int mdh)
        {
            if (Session["Username"] == null)
            {
                Session["Username"] = null;
                return RedirectToAction("Login", "Account");
            }
            else
            {
                CTDONHANG ctdh = db.CTDONHANGs.FirstOrDefault(p => p.MaDH == mdh);
                return View(ctdh);
            }
        }
    }
}

doan_qlDuan_CNTT/doan_qlDuan_CNTT/doan_qlDuan_CNTT/Areas/Admin/Views/DonHang/Create.cshtml
@model doan_qlDuan_CNTT.Areas.Admin.Models.DONHANG

@{
    ViewBag.Title = "Thêm đơn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Thêm đơn hàng</h2>

<div>
    <i class="fa fa-undo fa-fw"></i>@Html.ActionLink("Quay lại", "Index", "DonHang")
</div>

@using (Html.BeginForm("Create", "DonHang", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group col-lg-5">
        <label>Ngày mua</label>
        @Html.EditorFor(model => model.NgayMua, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập ngày mua..." } })
        <div class="text-danger">@Html.ValidationMessageFor(model => model.NgayMua)</div>
        <label>Ngày dự kiến giao</label>
        @Html.EditorFor(model => model.NgayDuKienGiao, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập ngày dự kiến giao..." } })
        <div class="text-danger">@Html.ValidationMessageFor(model => model.NgayDuKienGiao)</div>
        <label>Tình trạng</label>
        @Html.EditorFor(model => model.TinhTrang, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập tình trạng..." } })
        <div class="text-danger">@Html.ValidationMessageFor(model => model.TinhTrang)</div>
        <label>Mã khách hàng</label>
        @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập mã khách hàng..." } })
        <div class="text-danger">@Html.ValidationMessageFor(model => model.MaKH)</div>
        <br />
        <input type="submit" value="Tạo mới" class="btn btn-default" />
    </div>
    </div>
}

doan_qlDuan_CNTT/doan_qlDuan_CNTT/doan_qlDuan_CNTT/Areas/Admin/Views/DonHang/Details.cshtml
@model IEnumerable<doan_qlDuan_CNTT.Areas.Admin.Models.CTDONHANG>

@{
    ViewBag.Title = "Chi tiết đơn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Chi tiết đơn hàng</h2>
<div>
    <i class="fa fa-undo fa-fw"></i>@Html.ActionLink("Quay lại", "Index", "DonHang")
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaDH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DGBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThanhTien)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.MaDH)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.SoLuong)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DGBan)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.ThanhTien)
    </td>

</tr>
    }

</table>

doan_qlDuan_CNTT/doan_qlDuan_CNTT/doan_qlDuan_CNTT/Areas/Admin/Views/DonHang/Edit.cshtml
@model doan_qlDuan_CNTT.Areas.Admin.Models.DONHANG

@{
    ViewBag.Title = "Cập nhật đơn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Cập nhật đơn hàng</h2>
<div>
    <i class="fa fa-undo fa-fw"></i>@Html.ActionLink("Quay lại", "Index", "DonHang")
</div>

@using (Html.BeginForm("Edit", "DonHang", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group col-lg-5">
            @*<label>Mã đơn hàng</label>
            @Html.EditorFor(model => model.MaDH, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập mã đơn hàng..." } })
            <div class="text-danger">@Html.ValidationMessageFor(model => model.MaDH)</div>*@
            <label>Ngày mua</label>
            @Html.EditorFor(model => model.NgayMua, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập ngày mua..." } })
            <div class="text-danger">@Html.ValidationMessageFor(model => model.NgayMua)</div>
            <label>Ngày dự kiến giao</label>
            @Html.EditorFor(model => model.NgayDuKienGiao, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập ngày dự kiến giao..." } })
            <div class="text-danger">@Html.ValidationMessageFor(model => model.NgayDuKienGiao)</div>
            <label>Tình trạng</label>
            @Html.EditorFor(model => model.TinhTrang, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập tình trạng..." } })
            <div class="text-danger">@Html.ValidationMessageFor(model => model.TinhTrang)</div>
            <label>Mã khách hàng</label>
            @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nhập mã khách hàng..." } })
            <div class="text-danger">@Html.ValidationMessageFor(model => model.MaKH)</div>
            <br />
            <input type="submit" value="Cập nhật" class="btn btn-default" />
        </div>
    </div>
}

doan_qlDuan_CNTT/doan_qlDuan_CNTT/doan_qlDuan_CNTT/Areas/Admin/Views/DonHang/Index.cshtml
@model IEnumerable<doan_qlDuan_CNTT.Areas.Admin.Models.XemDonHangResult>

@{
    ViewBag.Title = "Đơn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Đơn hàng</h2>
<div class="col-lg-12">
    <div class="panel panel-default">
        <!-- /.panel-heading -->
        <div class="panel-collapse">
            <div class="table-responsive table-bordered">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Mã đơn hàng</th>
                            <th>Ngày mua</th>
                            <th>Ngày dự kiến giao</th>
                            <th>Tình trạng</th>
                            <th>Mã khách hàng <th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.MaDH)</td>
                            <td>@Html.DisplayFor(modelItem => item.NgayMua)</td>
                            <td>@Html.DisplayFor(modelItem => item.NgayDuKienGiao)</td>
                            <td>@Html.DisplayFor(modelItem => item.TinhTrang)</td>
                            <td>@Html.DisplayFor(modelItem => item.MaKH)</td>
                            <td>
                                @*<a href="@Url.Action("Edit", "DonHang", new { mdh = item.MaDH })"><i class="fa fa-pencil fa-fw"></i></a>|*@
                                <a href="@Url.Action("Index", "ChiTietDonHang", new { mdh = item.MaDH })"><i class="fa fa-list-alt fa-fw"></i></a>
                                <a onclick="return confirm('Bạn có chắc chắn muốn xoá đơn hàng này?')" href="@Url.Action("Delete", "DonHang", new { mdh = item.MaDH })"><i class="fa fa-times fa-fw"></i></a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>